[package]
name = "rouille"
version = "0.1.1"
edition = "2018"

[dependencies]
rouille = { git = "https://github.com/joxcat/rouille.git" }
auto_crime = { path = "../auto_crime_proc_macro/" }

[lib]
proc-macro = true
