[package]
name = "rouille"
version = "0.1.0"
edition = "2018"

[dependencies]
rouille = { git = "https://github.com/joxcat/rouille.git", rev = "0186b0508f746a431f997aa0f9da692515990a79" }

[lib]
proc-macro = true
